# Set envrionment variables in .vscode/settings.json

# File level variables 
@search-api-version = 2023-07-01-Preview
@datasource-name = rrfi-blob

###
# delete an existing datasource / start fresh
DELETE  https://{{env-search-name}}.search.windows.net/datasources/{{datasource-name}}
    ?api-version={{search-api-version}} HTTP/1.1
Content-Type: application/json
api-key: {{env-search-api-key}}


###
# create or update datasource from definition

PUT https://{{env-search-name}}.search.windows.net/datasources/{{datasource-name}}
    ?api-version={{search-api-version}} HTTP/1.1
Content-Type: application/json
api-key: {{env-search-api-key}}

{     
    "name":"{{datasource-name}}",
    "description" :"document storage location",  
    "type" : "azureblob",
    "credentials" : { "connectionString" : "{{env-storage-connstr-rrfisampledata}}" },  
    "container" : { 
        "name" : "rffi-shared-drive-data",
        "query": "Sample Data/SharedDrive_2024-02-01/HNL G Drive data/Flood Reports/2024"
     } 
} 

#< ../definitions/datasources/{{datasource-name}}.json