# Set envrionment variables in .vscode/settings.json

# File level variables 
@search-api-version = 2023-07-01-Preview
@index-name = geo-assets


###
# Simulate obtaining and transforming individual document metadata from upstream source
# (make sure VScode local liveserver is running at the root of the repo)

# @name sampleitem
# @prompt item-number
GET http://localhost:5500/sampledata/{{index-name}}-items/item{{item-number}}.json



###
# use the Azure Search push api to upload the document metadata to the search index
# NOTE: fields in the item must match the available index fields

POST https://{{search-name}}.search.windows.net/indexes/{{index-name}}/docs/index
    ?api-version={{search-api-version}} HTTP/1.1
Host: azuregigsearch.search.windows.net
Content-Type: application/json
api-key: {{search-api-key}}

{
    "value": [
        {{sampleitem.response.body.*}}
    ]
}
